added test project check in pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,13 +1,13 @@
 name: CI Pipeline
 
 on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+    push:
+        branches: [ main ]
+    pull_request:
+        branches: [ main ]
 
 jobs:
-  build:
+    build:
     runs-on: ubuntu-latest
 
     steps:
@@ -28,6 +28,15 @@ jobs:
       # Build project
       - name: Build
         run: dotnet build --no-restore --configuration Release
+        
+      - name: Check for test projects
+        run: |
+            if ! grep -q 'Microsoft.NET.Sdk.Test' ./**/*.csproj; then
+            echo "❌ No test projects found. Failing pipeline."
+            exit 1
+            else
+            echo "✅ Test project(s) detected."
+            fi
 
       # Run tests
       - name: Run Tests
